SET @db_name = DATABASE();
SET @exists = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db_name AND TABLE_NAME='customers' AND COLUMN_NAME='otp_token_hash');
SET @sql = IF(@exists=0,'ALTER TABLE customers ADD COLUMN otp_token_hash CHAR(64) NULL AFTER password_reset_last_sent_at','SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @exists = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db_name AND TABLE_NAME='customers' AND COLUMN_NAME='otp_expires_at');
SET @sql = IF(@exists=0,'ALTER TABLE customers ADD COLUMN otp_expires_at TIMESTAMP NULL AFTER otp_token_hash','SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @exists = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db_name AND TABLE_NAME='customers' AND COLUMN_NAME='otp_last_sent_at');
SET @sql = IF(@exists=0,'ALTER TABLE customers ADD COLUMN otp_last_sent_at TIMESTAMP NULL AFTER otp_expires_at','SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @exists = (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db_name AND TABLE_NAME='customers' AND COLUMN_NAME='otp_failed_attempts');
SET @sql = IF(@exists=0,'ALTER TABLE customers ADD COLUMN otp_failed_attempts TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER otp_last_sent_at','SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
