<?php
session_start();require_once '../shared/config.php';require_once '../shared/security.php';require_once '../shared/notifications.php';
if(!isset($_SESSION['admin_id'])){header('Location: login.php');exit;}o2oCsrfToken();$db=getDB();$adminId=(int)$_SESSION['admin_id'];$error='';$success='';
if($_SERVER['REQUEST_METHOD']==='POST'){o2oRequireCsrf();$id=(int)($_POST['id']??0);$status=$_POST['status']??'';$response=trim($_POST['admin_response']??'');if(!in_array($status,['open','in_review','resolved','closed'],true))$error='Invalid complaint status.';else{
 $st=$db->prepare("SELECT * FROM complaints WHERE id=? LIMIT 1");$st->execute([$id]);$c=$st->fetch();
 if(!$c)$error='Complaint not found.';
 elseif($response===''&&in_array($status,['resolved','closed'],true))$error='A response is required when resolving or closing a complaint.';
 else{
  $db->beginTransaction();
  try{
   $resolved=in_array($status,['resolved','closed'],true)?$adminId:null;$resolvedAt=$resolved?'NOW()':'NULL';
   $sql="UPDATE complaints SET status=?,admin_response=?,resolved_by=?,resolved_at=".$resolvedAt." WHERE id=?";
   $db->prepare($sql)->execute([$status,$response!==''?$response:null,$resolved,$id]);
   $db->prepare("INSERT INTO admin_actions(admin_id,action_type,target_type,target_id,details) VALUES(?,?,?,?,?)")->execute([$adminId,'complaint_'.$status,'complaint',$id,'Complaint status updated by admin.']);
   o2oNotifyCustomer($db,(int)$c['customer_id'],'complaint_update','Complaint update','Complaint #'.$id.' is now '.str_replace('_',' ',$status).'.'.($response!==''?' Admin response: '.$response:''));
   $db->commit();$success='Complaint #'.$id.' updated.';
  }catch(Throwable $e){if($db->inTransaction())$db->rollBack();$error='Could not update the complaint.';error_log('Complaint admin update failed: '.$e->getMessage());}
 }
}}
$filter=$_GET['status']??'';$allowed=['open','in_review','resolved','closed'];$where='';$args=[];if(in_array($filter,$allowed,true)){$where=' WHERE c.status=?';$args[]=$filter;}
$st=$db->prepare("SELECT c.*,cu.name customer_name,cu.email customer_email FROM complaints c JOIN customers cu ON cu.id=c.customer_id".$where." ORDER BY FIELD(c.status,'open','in_review','resolved','closed'),c.created_at DESC LIMIT 200");$st->execute($args);$rows=$st->fetchAll();
?><!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Complaints – Admin</title><style>body{font-family:Arial;background:#FAF6EE;color:#3D2B0F;margin:0}.nav{background:#1A1108;color:#C9A84C;padding:20px 30px}.nav a{color:#E8CC82;margin-left:18px}.main{max-width:1100px;margin:auto;padding:30px}.card{background:#fff;border:1px solid #E8E0D0;padding:18px;margin-bottom:15px}.meta{font-size:12px;color:#777}.field{margin:10px 0}.field label{display:block;font-size:11px;color:#777;margin-bottom:5px}.field select,.field textarea{width:100%;box-sizing:border-box;padding:9px;border:1px solid #ddd}.btn{background:#1A1108;color:#C9A84C;border:0;padding:10px 15px}.ok{background:#ECFDF5;color:#065F46;padding:10px;margin-bottom:15px}.err{background:#FEF2F2;color:#991B1B;padding:10px;margin-bottom:15px}.filters a{margin-right:12px}</style></head><body><div class="nav"><b>O2O Tradition · Admin</b><span><a href="dashboard.php">Dashboard</a><a href="audit.php">Audit Log</a><a href="users.php">Users</a></span></div><main class="main"><h1>Complaints & Disputes</h1><div class="filters"><a href="complaints.php">All</a><a href="complaints.php?status=open">Open</a><a href="complaints.php?status=in_review">In review</a><a href="complaints.php?status=resolved">Resolved</a><a href="complaints.php?status=closed">Closed</a></div><?php if($success):?><div class="ok"><?=htmlspecialchars($success)?></div><?php endif;?><?php if($error):?><div class="err"><?=htmlspecialchars($error)?></div><?php endif;?>
<?php foreach($rows as $x):?><section class="card"><h3>#<?=intval($x['id'])?> · <?=htmlspecialchars($x['subject'])?></h3><div class="meta"><?=htmlspecialchars($x['customer_name'])?> · <?=htmlspecialchars($x['customer_email'])?> · <?=htmlspecialchars($x['order_type'])?> #<?=intval($x['order_id'])?> · priority <?=htmlspecialchars($x['priority'])?> · <?=htmlspecialchars($x['status'])?></div><p><?=nl2br(htmlspecialchars($x['message']))?></p><?php if($x['admin_response']):?><p><b>Current response:</b><br><?=nl2br(htmlspecialchars($x['admin_response']))?></p><?php endif;?><form method="POST"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($_SESSION['csrf_token'])?>"><input type="hidden" name="id" value="<?=$x['id']?>"><div class="field"><label>Status</label><select name="status"><?php foreach(['open','in_review','resolved','closed'] as $s):?><option <?=$x['status']===$s?'selected':''?>><?=$s?></option><?php endforeach;?></select></div><div class="field"><label>Admin response</label><textarea name="admin_response" rows="3" placeholder="Required for resolved/closed"></textarea></div><button class="btn">Update Complaint</button></form></section><?php endforeach;if(!$rows):?><div class="card">No complaints match this filter.</div><?php endif;?></main></body></html>