<?php
session_start();require_once '../shared/config.php';require_once '../shared/security.php';require_once '../shared/payments.php';require_once '../shared/notifications.php';
o2oCsrfToken();if(!isset($_SESSION['admin_id'])){header('Location: login.php');exit;}$db=getDB();$adminId=(int)$_SESSION['admin_id'];$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){o2oRequireCsrf();$txId=(int)($_POST['transaction_id']??0);
 try{$db->beginTransaction();$st=$db->prepare("SELECT * FROM payment_transactions WHERE id=? AND status='paid' FOR UPDATE");$st->execute([$txId]);$tx=$st->fetch();if(!$tx)throw new RuntimeException('Payment is no longer eligible for refund.');if(!$tx['provider_payment_id'])throw new RuntimeException('Gateway payment ID is missing.');
  $refund=o2oRefundRazorpayPayment((string)$tx['provider_payment_id'],(float)$tx['amount']);$refundId=(string)($refund['id']??'');$db->prepare("UPDATE payment_transactions SET status='refunded',failure_reason=? WHERE id=? AND status='paid'")->execute(['Refunded via Razorpay refund '.$refundId,$txId]);if($db->rowCount()!==1)throw new RuntimeException('Refund state could not be recorded.');
  if($tx['order_type']==='rental'){$db->prepare("UPDATE orders SET payment_status='refunded',status=CASE WHEN status='new' THEN 'cancelled' ELSE status END WHERE id=? AND payment_status='paid'")->execute([(int)$tx['order_id']]);}
  else{$db->prepare("UPDATE purchase_orders SET payment_status='refunded',order_status=CASE WHEN order_status IN ('confirmed','packed') THEN 'cancelled' ELSE order_status END WHERE id=? AND payment_status='paid'")->execute([(int)$tx['order_id']]);$db->prepare("UPDATE product_modes pm JOIN purchase_order_items poi ON poi.item_id=pm.item_id SET pm.available=1 WHERE poi.order_id=? AND pm.mode='buy'")->execute([(int)$tx['order_id']]);$db->prepare("UPDATE items i JOIN purchase_order_items poi ON poi.item_id=i.id SET i.available=1 WHERE poi.order_id=?")->execute([(int)$tx['order_id']]);}
  $db->prepare("INSERT INTO admin_actions(admin_id,action,target_type,target_id,notes) VALUES(?,?,?,?,?)")->execute([$adminId,'payment_refund','payment_transaction',$txId,'Gateway refund '.$refundId.' for '.$tx['order_type'].' order #'.$tx['order_id']]);
  $customerId=(int)$tx['customer_id'];$db->commit();o2oNotifyCustomer($db,$customerId,'payment_refunded','Payment refunded','Payment for your '.$tx['order_type'].' order #'.str_pad((int)$tx['order_id'],6,'0',STR_PAD_LEFT).' has been refunded to the payment method.');$message='Refund completed successfully.';
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log('Admin payment refund failed: '.$e->getMessage());$error=$e->getMessage();}
}
$st=$db->query("SELECT pt.*,c.name customer_name FROM payment_transactions pt JOIN customers c ON c.id=pt.customer_id WHERE pt.status='paid' ORDER BY pt.paid_at DESC LIMIT 100");$payments=$st->fetchAll();
?><!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Payment Refunds</title><style>body{font-family:Arial;background:#FAF6EE;color:#3D2B0F;margin:0}.nav{background:#1A1108;color:#C9A84C;padding:20px 30px;display:flex;justify-content:space-between}.nav a{color:#E8CC82;text-decoration:none;margin-left:15px}.main{max-width:1050px;margin:auto;padding:30px}.card{background:#fff;border:1px solid #E8E0D0;padding:20px;margin-bottom:15px}.row{padding:15px 0;border-bottom:1px solid #eee;display:flex;justify-content:space-between;gap:15px}.btn{padding:9px 13px;background:#991B1B;color:#fff;border:0}.small{font-size:12px;color:#777}.ok{padding:12px;background:#DCFCE7}.err{padding:12px;background:#FEE2E2}@media(max-width:650px){.row{display:block}.row form{margin-top:10px}}</style></head><body><div class="nav"><b>O2O Tradition · Admin</b><div><a href="dashboard.php">Dashboard</a><a href="analytics.php">Analytics</a><a href="audit.php">Audit</a><a href="logout.php">Logout</a></div></div><main class="main"><h1>Payment Refunds</h1><p>Issue a full Razorpay refund for a paid online transaction. The gateway refund is performed before the local transaction is marked refunded.</p><?php if($message):?><div class="ok"><?=$message?></div><?php endif;?><?php if($error):?><div class="err"><?=htmlspecialchars($error)?></div><?php endif;?><section class="card"><?php if(!$payments):?><p class="small">No paid online transactions currently eligible for refund.</p><?php else:foreach($payments as $p):?><div class="row"><div><b><?=htmlspecialchars($p['order_type'])?> order #<?=str_pad((int)$p['order_id'],6,'0',STR_PAD_LEFT)?></b><div><?=htmlspecialchars($p['customer_name'])?> · ₹<?=number_format((float)$p['amount'],2)?> · <?=date('d M Y H:i',strtotime($p['paid_at']??$p['created_at']))?></div><div class="small">Razorpay payment <?=htmlspecialchars($p['provider_payment_id']??'—')?></div></div><form method="POST" onsubmit="return confirm('Issue a full refund for this payment?');"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($_SESSION['csrf_token'])?>"><input type="hidden" name="transaction_id" value="<?=$p['id']?>"><button class="btn">Full Refund</button></form></div><?php endforeach;endif;?></section></main></body></html>