<?php
session_start();require_once '../shared/config.php';
require_once '../shared/security.php';
o2oCsrfToken();if(!isset($_SESSION['admin_id'])){header('Location: login.php');exit;} $db=getDB();$adminId=(int)$_SESSION['admin_id'];$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  o2oRequireCsrf();
 $id=(int)($_POST['id']??0);$action=$_POST['action']??'';$allowed=['verified','rejected'];
 if(!in_array($action,$allowed,true)||$id<1)$error='Invalid moderation request.';
 else{$st=$db->prepare("SELECT * FROM vendor_verifications WHERE id=? AND status='pending'");$st->execute([$id]);$row=$st->fetch();
 if(!$row)$error='Pending verification record not found.';
 else{$db->beginTransaction();try{$db->prepare("UPDATE vendor_verifications SET status=?,verified_at=? WHERE id=?")->execute([$action,$action==='verified'?date('Y-m-d H:i:s'):null,$id]);$db->prepare("INSERT INTO admin_actions(admin_id,action,target_type,target_id,notes) VALUES(?,?,?,?,?)")->execute([$adminId,$action==='verified'?'verify_vendor':'reject_vendor_verification','vendor_verification',$id,'Admin moderation']);$db->commit();$message='Verification '.$action.'.';}catch(Throwable $e){$db->rollBack();$error='Could not save moderation decision.';}}}}
$st=$db->query("SELECT vv.*,v.store_name,v.email FROM vendor_verifications vv JOIN vendors v ON v.id=vv.vendor_id WHERE vv.status='pending' ORDER BY vv.created_at ASC");$rows=$st->fetchAll();
?><!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vendor Verification Moderation</title><style>body{font-family:Arial;background:#FAF6EE;color:#3D2B0F;margin:0}.nav{background:#1A1108;color:#C9A84C;padding:20px 30px;display:flex;justify-content:space-between}.nav a{color:#E8CC82;text-decoration:none}.main{max-width:1000px;margin:auto;padding:30px}.card{background:#fff;border:1px solid #E8E0D0;padding:20px;margin-bottom:15px}.btn{border:0;padding:10px 14px;margin-right:6px}.yes{background:#166534;color:#fff}.no{background:#991B1B;color:#fff}.small{font-size:12px;color:#777}.notice{padding:12px;background:#DCFCE7;margin-bottom:15px}.error{padding:12px;background:#FEE2E2;margin-bottom:15px}</style></head><body><div class="nav"><b>O2O Tradition · Admin</b><div><a href="dashboard.php">Dashboard</a> · <a href="logout.php">Logout</a></div></div><main class="main"><h1>Vendor Verification Review</h1><?php if($message):?><div class="notice"><?=htmlspecialchars($message)?></div><?php endif;?><?php if($error):?><div class="error"><?=htmlspecialchars($error)?></div><?php endif;?><?php if(!$rows):?><div class="card">No pending verification submissions.</div><?php else:foreach($rows as $r):?><div class="card"><h2><?=htmlspecialchars($r['store_name'])?></h2><div><?=htmlspecialchars(ucfirst($r['verification_type']))?> verification</div><div class="small"><?=htmlspecialchars($r['email'])?> · Submitted <?=date('d M Y, h:i A',strtotime($r['created_at']))?></div><p class="small">Document: <?php if(!empty($r['document_path'])):?><a href="verification_document.php?id=<?=$r['id']?>" target="_blank">View document securely</a><?php else:?>Not supplied<?php endif;?></p><form method="POST">
<input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token']) ?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn yes" name="action" value="verified">Approve</button><button class="btn no" name="action" value="rejected">Reject</button></form></div><?php endforeach;endif;?></main></body></html>