<?php
session_start();require_once '../shared/config.php';require_once '../shared/security.php';o2oCsrfToken();requireLogin('customer','login.php');$db=getDB();$answer='';$error='';$question=trim($_POST['question']??'');
function assistantLocalReply(PDO $db,int $customerId,string $q):?string{
 $l=strtolower($q);
 if(str_contains($l,'track')||str_contains($l,'where is my order')||str_contains($l,'order status')){
  $p=$db->prepare("SELECT id,order_status,created_at FROM purchase_orders WHERE customer_id=? ORDER BY created_at DESC LIMIT 5");$p->execute([$customerId]);$buy=$p->fetchAll();
  $r=$db->prepare("SELECT id,status,pickup_date,return_date FROM orders WHERE customer_id=? ORDER BY created_at DESC LIMIT 5");$r->execute([$customerId]);$rent=$r->fetchAll();$out=[];
  foreach($buy as $x)$out[]='Buy #'.str_pad($x['id'],6,'0',STR_PAD_LEFT).' — '.$x['order_status'];
  foreach($rent as $x)$out[]='Rental #'.str_pad($x['id'],6,'0',STR_PAD_LEFT).' — '.$x['status'].' (return '.$x['return_date'].')';
  return $out?'Your recent orders: '.implode('; ',$out).'.':'I do not see any orders on your account yet.';
 }
 if(str_contains($l,'return')||str_contains($l,'late'))return 'For a rental, check the order page for your return date. Late charges, when applicable, are calculated from the recorded return date. For a specific case, use the order details and vendor contact information.';
 if(str_contains($l,'size')||str_contains($l,'fit'))return 'Use your Size & Fit profile to save measurements. When a product has sizes, the selected product size can be carried into checkout.';
 if(str_contains($l,'buy'))return 'Choose Buy on the homepage or an item page with a Buy option. The current checkout supports Cash on Delivery.';
 if(str_contains($l,'rent'))return 'Choose Rent, open an available item, and select your pickup and return dates. The item page shows the rental price and trust information.';
 if(str_contains($l,'near')||str_contains($l,'map'))return 'Use the map to discover vendors by your area/pincode and open directions for stores with saved map coordinates.';
 if(str_contains($l,'review'))return 'Customer reviews are shown on item pages. AI review summaries are generated from recorded reviews when the AI provider is configured.';
 return null;
}
if($_SERVER['REQUEST_METHOD']==='POST'){
o2oRequireCsrf();
if($question!==''){
$key=getenv('OPENAI_API_KEY')?:'';if(!$key)$error='AI provider is not configured yet.';
else{$st=$db->query("SELECT i.id,i.name,i.category,i.quality,v.store_name, i.rent_per_day FROM items i JOIN vendors v ON v.id=i.vendor_id WHERE i.available=1 ORDER BY i.created_at DESC LIMIT 40");$items=$st->fetchAll();$catalog='';foreach($items as $i)$catalog.="ID {$i['id']} | {$i['name']} | category {$i['category']} | quality {$i['quality']} | rent/day ₹{$i['rent_per_day']} | store {$i['store_name']}\n";
$prompt="You are the O2O Tradition customer assistant. Answer the user's marketplace question clearly and briefly. Use ONLY the supplied catalogue for product claims. Do not invent products, prices, stores, availability, policies or order facts. If the question needs account/order data that is not supplied, say the customer should open My Orders or the relevant page. You can explain Rent, Buy, Sell, Swap, returns, trust records, sizing, AI stylist and navigation in general terms. Do not claim that an item is available for a particular date unless the supplied data proves it. User question: ".$question."\nCATALOGUE:\n".$catalog;
$payload=['model'=>getenv('O2O_AI_MODEL')?:'gpt-5.6-luna','input'=>[['role'=>'user','content'=>[['type'=>'input_text','text'=>$prompt]]]]];
$ch=curl_init('https://api.openai.com/v1/responses');curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>['Content-Type: application/json','Authorization: Bearer '.$key],CURLOPT_POSTFIELDS=>json_encode($payload),CURLOPT_TIMEOUT=>60]);$raw=curl_exec($ch);$http=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if($raw===false||$http<200||$http>=300)$error='AI request failed. Please try again.';else{$resp=json_decode($raw,true);$answer=$resp['output_text']??'';if(!$answer&&isset($resp['output']))foreach($resp['output'] as $o)foreach(($o['content']??[]) as $part)if(isset($part['text']))$answer.=$part['text'];if($answer==='')$error='The assistant returned no answer.';}}
}
}
?><!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>O2O Customer Assistant</title><style>body{font-family:Arial;background:#FAF6EE;color:#3D2B0F;margin:0}.nav{background:#1A1108;color:#C9A84C;padding:18px 28px}.nav a{color:#E8CC82;text-decoration:none;margin-left:18px}.main{max-width:850px;margin:auto;padding:30px}.hero,.card{background:#fff;border:1px solid #E8E0D0;padding:22px;margin-bottom:18px}.hero{background:#21170B;color:#fff}.input{width:100%;box-sizing:border-box;padding:14px;min-height:100px}.btn{margin-top:12px;background:#1A1108;color:#C9A84C;border:0;padding:12px 18px}.answer{white-space:pre-wrap;line-height:1.7}.error{background:#FEE2E2;color:#991B1B;padding:12px}</style></head><body><div class="nav"><b>O2O Tradition</b><a href="home.php">Home</a><a href="notifications.php">Notifications</a><a href="stylist.php">AI Stylist</a><a href="orders.php">Orders</a></div><main class="main"><section class="hero"><h1>🤖 O2O Customer Assistant</h1><p>Ask about discovering products, Rent, Buy, Sell, Swap, sizing, styling or marketplace navigation.</p></section><?php if($error):?><div class="error"><?=htmlspecialchars($error)?></div><?php endif;?><form class="card" method="POST"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token']) ?>"><textarea class="input" name="question" required placeholder="Example: What should I wear for a wedding under ₹2500?"><?=htmlspecialchars($question)?></textarea><button class="btn">Ask O2O Assistant</button></form><?php if($answer):?><section class="card"><h2>Assistant</h2><div class="answer"><?=htmlspecialchars($answer)?></div><p style="font-size:11px;color:#888">AI-generated guidance. Product availability can change.</p></section><?php endif;?></main></body></html>