<?php
session_start();require_once '../shared/config.php';require_once '../shared/security.php';o2oCsrfToken();requireLogin('customer','login.php');$db=getDB();$result=null;$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 o2oRequireCsrf();
 if(($_POST['action']??'')==='save_look'){
  $lookData=json_decode((string)($_POST['look_data']??''),true);
  if(!is_array($lookData)){$error='This look could not be saved.';}
  else{$occasion=trim((string)($_POST['occasion']??''));$mode=$_POST['mode']??'rent';$budget=(float)($_POST['budget']??0);$style=trim((string)($_POST['style']??''));$colors=trim((string)($_POST['colors']??''));$intro=trim((string)($_POST['intro']??''));if($occasion===''||!in_array($mode,['rent','buy'],true))$error='Invalid complete look.';else{$db->prepare("INSERT INTO saved_complete_looks(customer_id,occasion,mode,budget,style,colors,intro,look_data) VALUES(?,?,?,?,?,?,?,?)")->execute([(int)$_SESSION['customer_id'],$occasion,$mode,$budget>0?$budget:null,$style!==''?$style:null,$colors!==''?$colors:null,$intro!==''?$intro:null,json_encode($lookData,JSON_UNESCAPED_UNICODE)]);$message='Complete look saved to your profile.';}}
  }
  else {
 $occasion=trim($_POST['occasion']??'');$budget=(float)($_POST['budget']??0);$style=trim($_POST['style']??'');$colors=trim($_POST['colors']??'');$mode=$_POST['mode']??'rent';
 if(!$occasion||!in_array($mode,['rent','buy'],true))$error='Please choose an occasion and mode.';
 else{$key=getenv('OPENAI_API_KEY')?:'';
  if(!$key)$error='AI provider is not configured yet.';
  else{
   $sql="SELECT i.id,i.name,i.description,i.category,i.quality,v.store_name,pm.mode,pm.price FROM items i JOIN vendors v ON v.id=i.vendor_id JOIN product_modes pm ON pm.item_id=i.id AND pm.mode=? AND pm.available=1 WHERE i.available=1";$params=[$mode];if($budget>0){$sql.=" AND pm.price<=?";$params[]=$budget;}$sql.=" ORDER BY i.name LIMIT 50";$s=$db->prepare($sql);$s->execute($params);$catalog=$s->fetchAll();
   if(!$catalog)$error='No matching items are available.';
   else{$catalogText='';foreach($catalog as $p){$catalogText.="ID ".$p['id']." | ".$p['name']." | category: ".$p['category']." | quality: ".$p['quality']." | price: ".$p['price']." | store: ".$p['store_name']." | description: ".$p['description']."\n";}
    $prompt="You are the O2O Tradition AI Complete Look Stylist. Use ONLY the supplied catalogue. Never invent products, IDs, prices, stores or availability. User: occasion=".$occasion."; budget=".($budget>0?'₹'.$budget:'no limit')."; style=".$style."; colors=".$colors."; mode=".$mode.". Return ONLY valid JSON with keys: intro, looks (array of up to 3 objects with item_id, why, styling_tips, jewellery, footwear, bag_or_accessory), fallback_advice. Jewellery, footwear and bag_or_accessory must be generic styling suggestions unless matching catalogue items are supplied; never claim they are sold by O2O Tradition.\nCATALOGUE:\n".$catalogText;
    $payload=['model'=>getenv('O2O_AI_MODEL')?:'gpt-5.6-luna','input'=>[['role'=>'user','content'=>[['type'=>'input_text','text'=>$prompt]]]]];
    $ch=curl_init('https://api.openai.com/v1/responses');curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>['Content-Type: application/json','Authorization: Bearer '.$key],CURLOPT_POSTFIELDS=>json_encode($payload),CURLOPT_TIMEOUT=>60]);$raw=curl_exec($ch);$http=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);
    if($raw===false||$http<200||$http>=300)$error='AI request failed. Please try again.';
    else{$resp=json_decode($raw,true);$text=$resp['output_text']??'';if(!$text&&isset($resp['output']))foreach($resp['output'] as $o)foreach(($o['content']??[]) as $part)if(isset($part['text']))$text.=$part['text'];$data=json_decode(trim($text),true);
     if(!is_array($data))$error='AI returned an unreadable complete look.';else{$valid=[];foreach(($data['looks']??[]) as $look){$id=(int)($look['item_id']??0);foreach($catalog as $p)if((int)$p['id']===$id){$look['product']=$p;$valid[]=$look;break;}}$data['looks']=$valid;$result=$data;}
    }
   }
  }
 }
 }
}
?><!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI Complete Look</title><style>
body{font-family:Arial;background:#FAF6EE;color:#3D2B0F;margin:0}.nav{background:#1A1108;color:#C9A84C;padding:18px 28px;display:flex;justify-content:space-between}.nav a{color:#E8CC82;margin-left:15px;text-decoration:none}.main{max-width:950px;margin:auto;padding:30px}.hero{background:#28170c;color:#fff;padding:26px;margin-bottom:18px}.card{background:#fff;padding:24px;margin-bottom:18px;border:1px solid #E8E0D0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.label{display:block;font-size:11px;font-weight:bold;margin:8px 0}.input,.select{width:100%;padding:11px;box-sizing:border-box}.btn{margin-top:15px;padding:12px 18px;background:#1A1108;color:#C9A84C;border:0}.error{background:#FEF2F2;color:#991B1B;padding:12px;margin-bottom:15px}.look{border-top:1px solid #eee;padding:18px 0}.look a{color:#8B1A1A}.piece{background:#F6F0E5;padding:9px;margin:7px 0}.small{color:#777;font-size:12px}@media(max-width:650px){.grid{grid-template-columns:1fr}}</style></head><body>
<div class="nav"><b>O2O Tradition</b><div><a href="home.php">Home</a><a href="stylist.php">AI Stylist</a><a href="saved_looks.php">Saved Looks</a></div></div><main class="main"><section class="hero"><h1>✦ AI Complete Look</h1><p>Build a full traditional look around a real catalogue item: outfit, jewellery, footwear and finishing accessories.</p></section>
<?php if($error):?><div class="error"><?=htmlspecialchars($error)?></div><?php endif;?>
<form class="card" method="POST">
<input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token']) ?>"><div class="grid"><div><label class="label">Occasion</label><select class="select" name="occasion" required><option value="">Choose</option><?php foreach(['Wedding','Haldi / Mehendi','Festival','College Fest','Traditional Day','Cultural Event','Photoshoot'] as $x):?><option><?=$x?></option><?php endforeach;?></select></div><div><label class="label">Mode</label><select class="select" name="mode"><option value="rent">Rent</option><option value="buy">Buy</option></select></div><div><label class="label">Maximum outfit budget ₹</label><input class="input" type="number" min="0" name="budget" placeholder="2500"></div><div><label class="label">Preferred style</label><input class="input" name="style" placeholder="Royal, minimal, festive..."></div><div><label class="label">Preferred colours</label><input class="input" name="colors" placeholder="Maroon, gold, pastel..."></div></div><button class="btn">✨ Create Complete Look</button></form>
<?php if($result):?><section class="card"><h2><?=htmlspecialchars($result['intro']??'Your complete look')?></h2><?php foreach($result['looks'] as $look):$p=$look['product'];?><div class="look"><h3><a href="item.php?id=<?=(int)$p['id']?>"><?=htmlspecialchars($p['name'])?></a></h3><div class="small"><?=htmlspecialchars($p['store_name'])?> · ₹<?=number_format((float)$p['price'],0)?></div><p><?=htmlspecialchars($look['why']??'')?></p><div class="piece"><b>💎 Jewellery:</b> <?=htmlspecialchars($look['jewellery']??'')?></div><div class="piece"><b>👞 Footwear:</b> <?=htmlspecialchars($look['footwear']??'')?></div><div class="piece"><b>👜 Bag / Accessory:</b> <?=htmlspecialchars($look['bag_or_accessory']??'')?></div><p><b>Styling:</b> <?=htmlspecialchars($look['styling_tips']??'')?></p></div><?php endforeach;?><p class="small"><?=htmlspecialchars($result['fallback_advice']??'')?></p><form method="POST" style="margin:12px 0"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($_SESSION['csrf_token'])?>"><input type="hidden" name="action" value="save_look"><input type="hidden" name="occasion" value="<?=htmlspecialchars($_POST['occasion']??'')?>"><input type="hidden" name="mode" value="<?=htmlspecialchars($_POST['mode']??'rent')?>"><input type="hidden" name="budget" value="<?=htmlspecialchars($_POST['budget']??'')?>"><input type="hidden" name="style" value="<?=htmlspecialchars($_POST['style']??'')?>"><input type="hidden" name="colors" value="<?=htmlspecialchars($_POST['colors']??'')?>"><input type="hidden" name="intro" value="<?=htmlspecialchars($result['intro']??'')?>"><input type="hidden" name="look_data" value="<?=htmlspecialchars(json_encode($result['looks'],JSON_UNESCAPED_UNICODE))?>"><button class="btn">♡ Save This Complete Look</button></form><p class="small">Only the outfit link and price above are catalogue-backed. Accessories are styling suggestions unless separately listed.</p></section><?php endif;?></main></body></html>