<?php
session_start();require_once '../shared/config.php';require_once '../shared/security.php';o2oCsrfToken();requireLogin('customer','login.php');
$db=getDB();$customerId=(int)$_SESSION['customer_id'];$message='';
if($_SERVER['REQUEST_METHOD']==='POST'){o2oRequireCsrf();$type=$_POST['event_type']??'';$allowed=['upcycled'];if(in_array($type,$allowed,true)){ $note=trim($_POST['note']??'');$st=$db->prepare("INSERT INTO eco_events(customer_id,event_type,source_id,reuse_count,note) VALUES(?,?,NULL,1,?)");$st->execute([$customerId,$type,$note?:null]);$message='Your circular-fashion activity was added.';}}
$rent=$db->prepare("SELECT COUNT(*) FROM orders WHERE customer_id=? AND status='completed'");$rent->execute([$customerId]);$rentalCount=(int)$rent->fetchColumn();
$swap=$db->prepare("SELECT COUNT(*) FROM swap_requests sr JOIN swap_listings sl ON sl.id=sr.swap_listing_id WHERE sr.requester_id=? AND sr.status='completed'");$swap->execute([$customerId]);$swapCount=(int)$swap->fetchColumn();
$resale=$db->prepare("SELECT COUNT(*) FROM seller_listings WHERE seller_id=? AND status='sold'");$resale->execute([$customerId]);$resaleCount=(int)$resale->fetchColumn();
$up=$db->prepare("SELECT COUNT(*) FROM eco_events WHERE customer_id=? AND event_type='upcycled'");$up->execute([$customerId]);$upCount=(int)$up->fetchColumn();
$total=$rentalCount+$swapCount+$resaleCount+$upCount;
$events=$db->prepare("SELECT event_type,reuse_count,note,created_at FROM eco_events WHERE customer_id=? ORDER BY created_at DESC LIMIT 10");$events->execute([$customerId]);$events=$events->fetchAll();
?><!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Eco & Circular Fashion – O2O Tradition</title><style>
body{font-family:Arial;background:#F5F3EA;color:#30402D;margin:0}.nav{background:#1A1108;color:#C9A84C;padding:18px 28px;display:flex;justify-content:space-between}.nav a{color:#E8CC82;margin-left:15px;text-decoration:none}.main{max-width:950px;margin:auto;padding:30px}.hero,.card{background:#fff;border:1px solid #DDD8C8;padding:24px;margin-bottom:18px}.hero{background:#233526;color:#fff}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stat{background:#F1F5ED;padding:18px;border:1px solid #D8E0D2}.num{font-size:30px}.label{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#697463}.form{display:flex;gap:10px}.input{flex:1;padding:11px;border:1px solid #ddd}.btn{background:#30402D;color:#fff;border:0;padding:11px 18px}.msg{background:#EAF5E8;padding:12px;margin-bottom:15px}.small{font-size:12px;color:#697463;line-height:1.6}.badge{display:inline-block;padding:5px 9px;background:#E5F0DF;margin:4px;border-radius:15px;font-size:11px}@media(max-width:650px){.stats{grid-template-columns:1fr 1fr}.form{flex-direction:column}}
</style></head><body><div class="nav"><b>O2O Tradition</b><div><a href="home.php">Home</a><a href="rewards.php">Rewards</a></div></div><main class="main"><section class="hero"><h1>♻ Eco & Circular Fashion</h1><p>See how your Rent, Swap, Resale and upcycling activity keeps traditional fashion in circulation.</p></section><?php if($message):?><div class="msg"><?=htmlspecialchars($message)?></div><?php endif;?><section class="card"><div class="stats"><div class="stat"><div class="num"><?=$rentalCount?></div><div class="label">Completed rentals</div></div><div class="stat"><div class="num"><?=$swapCount?></div><div class="label">Completed swaps</div></div><div class="stat"><div class="num"><?=$resaleCount?></div><div class="label">Resales</div></div><div class="stat"><div class="num"><?=$upCount?></div><div class="label">Upcycled</div></div></div><p class="small" style="margin-top:15px"><b><?=$total?></b> recorded circular-fashion activities. These counts describe marketplace activity; they are not a scientific measurement of carbon or waste avoided.</p></section><section class="card"><h2>Eco-Luxe / Upcycled</h2><p class="small">Did you upcycle a traditional garment or accessory? Record it here so your circular-fashion history stays visible.</p><form class="form" method="POST"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($_SESSION['csrf_token'])?>"><input type="hidden" name="event_type" value="upcycled"><input class="input" name="note" maxlength="255" placeholder="e.g. Restyled an old silk saree into a festive outfit"><button class="btn">Record Activity</button></form></section><section class="card"><h2>Your circular history</h2><?php foreach($events as $e):?><div class="badge"><?=htmlspecialchars(str_replace('_',' ',$e['event_type']))?> · <?=date('d M Y',strtotime($e['created_at']))?><?php if($e['note']):?> · <?=htmlspecialchars($e['note'])?><?php endif;?></div><?php endforeach;?><?php if(!$events):?><p class="small">No manually recorded circular activities yet. Completed marketplace activity is reflected in the summary above.</p><?php endif;?></section><section class="card"><b>About the metric</b><p class="small">O2O Tradition records reuse-related marketplace actions rather than estimating environmental impact. A rental, swap or resale represents an additional circulation event, but the platform does not claim a specific carbon or waste saving from an individual transaction.</p></section></main></body></html>