<?php
session_start();require_once '../shared/config.php';
require_once '../shared/security.php';
o2oCsrfToken();requireLogin('customer','login.php');$db=getDB();$customerId=(int)$_SESSION['customer_id'];
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='read'){ $id=(int)($_POST['id']??0);$db->prepare("UPDATE notifications SET is_read=1 WHERE id=? AND customer_id=?")->execute([$id,$customerId]);header('Location: notifications.php');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='all_read'){$db->prepare("UPDATE notifications SET is_read=1 WHERE customer_id=?")->execute([$customerId]);header('Location: notifications.php');exit;}
$st=$db->prepare("SELECT * FROM notifications WHERE customer_id=? ORDER BY created_at DESC LIMIT 100");$st->execute([$customerId]);$notifications=$st->fetchAll();$unread=0;foreach($notifications as $n)$unread+=(int)!$n['is_read'];
?><!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Notifications – O2O Tradition</title><style>
body{font-family:Arial;background:#FAF6EE;color:#3D2B0F;margin:0}.nav{background:#1A1108;color:#C9A84C;padding:18px 28px;display:flex;justify-content:space-between}.nav a{color:#E8CC82;text-decoration:none;margin-left:18px}.main{max-width:850px;margin:auto;padding:30px}.head{background:#fff;border:1px solid #E8E0D0;padding:22px;margin-bottom:18px;display:flex;justify-content:space-between;align-items:center}.btn{background:#1A1108;color:#C9A84C;border:0;padding:10px 14px}.notice{background:#fff;border:1px solid #E8E0D0;margin-bottom:10px;padding:17px;display:flex;justify-content:space-between;gap:15px}.notice.unread{border-left:4px solid #C9A84C;background:#FFFDF6}.type{font-size:10px;text-transform:uppercase;letter-spacing:1.5px;color:#8B1A1A}.title{font-weight:bold;margin:5px 0}.msg{font-size:13px;line-height:1.5;color:#666}.date{font-size:11px;color:#999}.smallbtn{border:1px solid #ddd;background:#fff;padding:7px 9px;font-size:11px}.empty{text-align:center;padding:60px;color:#888}</style></head><body><div class="nav"><b>O2O Tradition</b><div><a href="home.php">Home</a><a href="orders.php">Orders</a></div></div><main class="main"><div class="head"><div><h1 style="margin:0;font:32px Georgia,serif">🔔 Notifications</h1><div style="color:#777;margin-top:5px"><?=$unread?> unread</div></div><?php if($unread):?><form method="POST">
<input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token']) ?>"><input type="hidden" name="action" value="all_read"><button class="btn">Mark all read</button></form><?php endif;?></div><?php if(!$notifications):?><div class="empty">No notifications yet.<br><br>Order and marketplace updates will appear here.</div><?php else:foreach($notifications as $n):?><div class="notice <?=$n['is_read']?'':'unread'?>"><div><div class="type"><?=htmlspecialchars($n['type'])?></div><div class="title"><?=htmlspecialchars($n['title'])?></div><div class="msg"><?=htmlspecialchars($n['message'])?></div><div class="date"><?=date('d M Y, h:i A',strtotime($n['created_at']))?></div></div><?php if(!$n['is_read']):?><form method="POST">
<input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token']) ?>"><input type="hidden" name="action" value="read"><input type="hidden" name="id" value="<?=$n['id']?>"><button class="smallbtn">Mark read</button></form><?php endif;?></div><?php endforeach;endif;?></main></body></html>