<?php
session_start();require_once '../shared/config.php';requireLogin('customer','login.php');$db=getDB();
$stmt=$db->prepare("SELECT o.*,i.name item_name,i.image_path,v.store_name FROM orders o JOIN items i ON o.item_id=i.id JOIN vendors v ON o.vendor_id=v.id WHERE o.customer_id=? ORDER BY o.created_at DESC");$stmt->execute([$_SESSION['customer_id']]);$orders=$stmt->fetchAll();

$trustByOrder=[];
if($orders){
  $orderIds=array_column($orders,'id');$placeholders=implode(',',array_fill(0,count($orderIds),'?'));
  $trustStmt=$db->prepare("SELECT cr.rental_order_id,cr.inspection_type,cr.condition_score,cr.created_at
      FROM condition_reports cr JOIN orders o ON o.id=cr.rental_order_id
      WHERE o.customer_id=? AND cr.rental_order_id IN ($placeholders)
      ORDER BY cr.created_at DESC");
  $trustStmt->execute(array_merge([$_SESSION['customer_id']],$orderIds));
  foreach($trustStmt->fetchAll() as $tr){$oid=(int)$tr['rental_order_id'];$type=$tr['inspection_type'];if(!isset($trustByOrder[$oid]))$trustByOrder[$oid]=[];if(!isset($trustByOrder[$oid][$type]))$trustByOrder[$oid][$type]=$tr;}

  $sanStmt=$db->prepare("SELECT sr.rental_order_id,sr.status,sr.completed_at,sr.created_at
      FROM sanitization_records sr JOIN orders o ON o.id=sr.rental_order_id
      WHERE o.customer_id=? AND sr.rental_order_id IN ($placeholders)
      ORDER BY sr.created_at DESC");
  $sanStmt->execute(array_merge([$_SESSION['customer_id']],$orderIds));
  foreach($sanStmt->fetchAll() as $sr){$oid=(int)$sr['rental_order_id'];if(!isset($trustByOrder[$oid]))$trustByOrder[$oid]=[];if(!isset($trustByOrder[$oid]['sanitization']))$trustByOrder[$oid]['sanitization']=$sr;}
}
$buyStmt=$db->prepare("SELECT po.*,poi.item_id,poi.quantity,poi.unit_price,poi.total_price,i.name item_name,i.image_path,v.store_name
    FROM purchase_orders po
    JOIN purchase_order_items poi ON poi.order_id=po.id
    JOIN items i ON i.id=poi.item_id
    LEFT JOIN vendors v ON v.id=po.vendor_id
    WHERE po.customer_id=? ORDER BY po.created_at DESC");
$buyStmt->execute([$_SESSION['customer_id']]);$buyOrders=$buyStmt->fetchAll();
$labels=['new'=>'⏳ New Order','in_progress'=>'🚀 In Progress / Rented','completed'=>'✅ Completed / Returned'];
$buySteps=['confirmed'=>'Confirmed','packed'=>'Packed','shipped'=>'Shipped','delivered'=>'Delivered'];
$sellPurchaseStmt=$db->prepare("SELECT spo.*,sl.title,sl.image_path,c.name seller_name FROM seller_purchase_orders spo JOIN seller_listings sl ON sl.id=spo.listing_id JOIN customers c ON c.id=spo.seller_id WHERE spo.buyer_id=? ORDER BY spo.created_at DESC");
$sellPurchaseStmt->execute([$_SESSION['customer_id']]);$sellPurchases=$sellPurchaseStmt->fetchAll();
?><!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My Orders – O2O Tradition</title><style>
body{font-family:Arial,sans-serif;background:#FAF6EE;color:#3D2B0F;margin:0}.nav{height:64px;background:#1A1108;color:#C9A84C;display:flex;align-items:center;justify-content:space-between;padding:0 40px}.logo{font:28px Georgia,serif}.nav a{color:#E8CC82;text-decoration:none;margin-left:15px}.header{background:#fff;padding:30px 40px;border-bottom:1px solid #E8E0D0}.title{font:34px Georgia,serif}.main{max-width:900px;margin:auto;padding:30px 40px}.card{background:#fff;margin-bottom:20px;box-shadow:0 2px 12px #0000000f}.head,.foot{padding:14px 20px;border-bottom:1px solid #E8E0D0;display:flex;justify-content:space-between}.body{padding:20px;display:flex;gap:16px}.img{width:80px;height:80px;background:#E8E0D0;display:flex;align-items:center;justify-content:center;font-size:28px}.img img{width:80px;height:80px;object-fit:cover}.name{font:20px Georgia,serif}.store{color:#C9A84C;font-size:12px;margin:5px 0 10px}.meta{color:#666;font-size:13px;display:flex;gap:18px;flex-wrap:wrap}.foot{border-top:1px solid #E8E0D0;border-bottom:0;background:#FDFAF5}.status{padding:5px 10px;border-radius:20px;font-size:12px}.tracking{margin:0 20px 20px;padding:16px;background:#FAF6EE;border:1px solid #E8E0D0}.tracking-title{font-size:12px;color:#777;margin-bottom:12px}.steps{display:flex;gap:6px;align-items:center}.step{flex:1;text-align:center;font-size:11px;color:#999}.dot{width:22px;height:22px;border-radius:50%;background:#ddd;margin:0 auto 5px;display:flex;align-items:center;justify-content:center}.step.active{color:#3D2B0F;font-weight:bold}.step.active .dot{background:#C9A84C;color:#1A1108}.line{height:2px;flex:0 0 18px;background:#ddd;margin-bottom:17px}.line.active{background:#C9A84C}.trust{margin:0 20px 20px;padding:15px;background:#FDFAF5;border:1px solid #E8E0D0}.trust-title{font-size:12px;color:#777;margin-bottom:10px}.trust-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.trust-box{border:1px solid #E8E0D0;background:#fff;padding:9px;font-size:12px}.trust-label{font-size:9px;text-transform:uppercase;letter-spacing:.8px;color:#999;margin-bottom:4px}.trust-ok{color:#166534;font-weight:bold}.trust-muted{color:#888}@media(max-width:650px){.trust-grid{grid-template-columns:1fr}}
.empty{text-align:center;padding:70px;color:#888}.empty a{display:inline-block;margin-top:15px;padding:12px 24px;background:#1A1108;color:#C9A84C;text-decoration:none}@media(max-width:650px){.main{padding:20px}.nav,.header{padding-left:20px;padding-right:20px}}</style></head><body>
<div class="nav"><div class="logo">O2O Tradition</div><div><a href="home.php">Home</a><a href="logout.php">Logout</a></div></div><div class="header"><div class="title">My Orders</div><div><?=count($orders)+count($buyOrders)?> order(s) placed · <?=count($orders)?> rent · <?=count($buyOrders)?> buy</div></div><div class="main">
<h2 style="font:28px Georgia,serif;margin:0 0 18px">🛍 Buy Orders</h2>
<?php if($buyOrders): foreach($buyOrders as $o): ?>
<div class="card"><div class="head"><div>Buy Order #<?=str_pad($o['id'],6,'0',STR_PAD_LEFT)?><div style="font-size:12px;color:#aaa"><?=date('d M Y, h:i A',strtotime($o['created_at']))?></div></div><div class="status"><?=htmlspecialchars(ucfirst($o['order_status']))?></div></div>
<div class="body"><div class="img"><?php if($o['image_path']&&file_exists('../uploads/items/'.$o['image_path'])):?><img src="../uploads/items/<?=htmlspecialchars($o['image_path'])?>"><?php else:?>🛍️<?php endif;?></div><div><div class="name"><?=htmlspecialchars($o['item_name'])?></div><div class="store">🏬 <?=htmlspecialchars($o['store_name']??'Marketplace seller')?></div><div class="meta"><span>🔢 Quantity: <b><?=intval($o['quantity'])?></b></span><span>💳 <b>Cash on Delivery</b></span><span>📦 Payment: <b><?=htmlspecialchars($o['payment_status'])?></b></span></div></div></div>
<div class="tracking"><div class="tracking-title">📦 Delivery Tracking</div><div class="steps"><?php $current=array_search($o['order_status'],array_keys($buySteps),true); if($current===false)$current=-1; $stepIndex=0; foreach($buySteps as $stepKey=>$stepLabel): if($stepIndex>0): ?><div class="line <?=$stepIndex<=$current?'active':''?>"></div><?php endif; ?><div class="step <?=$stepIndex<=$current?'active':''?>"><div class="dot"><?=$stepIndex<$current?'✓':($stepIndex===$current?'•':'')?></div><?=htmlspecialchars($stepLabel)?></div><?php $stepIndex++; endforeach; ?></div><?php if($o['order_status']==='cancelled'): ?><div style="margin-top:10px;color:#B91C1C;font-size:13px">This order was cancelled by the seller.</div><?php endif; ?></div>
<div class="foot"><div>Purchase Total: <b style="color:#8B1A1A">₹<?=number_format($o['total_price'],0)?></b></div><div>Order Status: <b><?=htmlspecialchars(ucfirst($o['order_status']))?></b></div></div></div>
<?php endforeach; else: ?><div class="empty" style="padding:30px"><p>No buy orders yet.</p></div><?php endif; ?>
<h2 style="font:28px Georgia,serif;margin:35px 0 18px">♻ Pre-Owned Purchases</h2>
<?php if($sellPurchases): foreach($sellPurchases as $sp): ?>
<div class="card"><div class="head"><div>Seller Order #<?=str_pad($sp['id'],6,'0',STR_PAD_LEFT)?><div style="font-size:12px;color:#aaa"><?=date('d M Y, h:i A',strtotime($sp['created_at']))?></div></div><div class="status"><?=htmlspecialchars(ucfirst($sp['order_status']))?></div></div>
<div class="body"><div class="img"><?php if($sp['image_path']&&file_exists('../uploads/sell/'.$sp['image_path'])):?><img src="../uploads/sell/<?=htmlspecialchars($sp['image_path'])?>"><?php else:?>♻️<?php endif;?></div><div><div class="name"><?=htmlspecialchars($sp['title'])?></div><div class="store">👤 Seller: <?=htmlspecialchars($sp['seller_name'])?></div><div class="meta"><span>💳 <b>Cash on Delivery</b></span><span>📦 Payment: <b><?=htmlspecialchars($sp['payment_status'])?></b></span></div></div></div>
<div class="tracking"><div class="tracking-title">📦 Delivery Tracking</div><div class="steps"><?php $spSteps=['confirmed'=>'Confirmed','packed'=>'Packed','shipped'=>'Shipped','delivered'=>'Delivered'];$current=array_search($sp['order_status'],array_keys($spSteps),true);if($current===false)$current=-1;$si=0;foreach($spSteps as $sk=>$sl):if($si>0):?><div class="line <?=$si<=$current?'active':''?>"></div><?php endif;?><div class="step <?=$si<=$current?'active':''?>"><div class="dot"><?=$si<$current?'✓':($si===$current?'•':'')?></div><?=htmlspecialchars($sl)?></div><?php $si++;endforeach;?></div></div>
<div class="foot"><div>Purchase Total: <b style="color:#8B1A1A">₹<?=number_format($sp['total_amount'],0)?></b></div><div>Seller Order Status: <b><?=htmlspecialchars(ucfirst($sp['order_status']))?></b></div></div></div>
<?php endforeach; else: ?><div class="empty" style="padding:30px"><p>No pre-owned purchases yet.</p></div><?php endif; ?>
<h2 style="font:28px Georgia,serif;margin:35px 0 18px">👘 Rental Orders</h2>
<?php if($orders): foreach($orders as $o): ?><div class="card"><div class="head"><div>Order #<?=str_pad($o['id'],6,'0',STR_PAD_LEFT)?><div style="font-size:12px;color:#aaa"><?=date('d M Y, h:i A',strtotime($o['created_at']))?></div></div><div style="font-size:11px;margin-top:5px"><a href="rental_tracking.php?id=<?=$o['id']?>" style="color:#8B1A1A">View rental lifecycle</a></div><div class="status"><?=htmlspecialchars($labels[$o['status']]??$o['status'])?></div></div><div class="body"><div class="img"><?php if($o['image_path']&&file_exists('../uploads/items/'.$o['image_path'])):?><img src="../uploads/items/<?=htmlspecialchars($o['image_path'])?>"><?php else:?>👘<?php endif;?></div><div><div class="name"><?=htmlspecialchars($o['item_name'])?></div><div class="store">🏬 <?=htmlspecialchars($o['store_name'])?></div><div class="meta"><span>📅 Pickup: <b><?=date('d M Y',strtotime($o['pickup_date']))?></b></span><span>🔄 Return: <b><?=date('d M Y',strtotime($o['return_date']))?></b></span><span>💳 <b><?=htmlspecialchars($o['payment_method'])?></b></span></div></div></div><?php $trust=$trustByOrder[(int)$o['id']]??[]; ?>
<div class="trust"><div class="trust-title">🔐 Trust Protocol</div><div class="trust-grid">
<div class="trust-box"><div class="trust-label">Before-rental inspection</div><?php if(isset($trust['before_rental'])):?><div class="trust-ok">✓ Recorded</div><div><?=number_format((float)$trust['before_rental']['condition_score'],1)?>/100 · <?=date('d M Y',strtotime($trust['before_rental']['created_at']))?></div><?php else:?><div class="trust-muted">Not recorded</div><?php endif;?></div>
<div class="trust-box"><div class="trust-label">Sanitization</div><?php if(isset($trust['sanitization'])):?><div class="<?= $trust['sanitization']['status']==='completed'?'trust-ok':'' ?>"><?=htmlspecialchars(ucwords(str_replace('_',' ',$trust['sanitization']['status'])))?></div><?php if($trust['sanitization']['completed_at']):?><div>Completed <?=date('d M Y',strtotime($trust['sanitization']['completed_at']))?></div><?php endif;?><?php else:?><div class="trust-muted">No record yet</div><?php endif;?></div>
<div class="trust-box"><div class="trust-label">After-return inspection</div><?php if(isset($trust['after_return'])):?><div class="trust-ok">✓ Recorded</div><div><?=number_format((float)$trust['after_return']['condition_score'],1)?>/100 · <?=date('d M Y',strtotime($trust['after_return']['created_at']))?></div><?php else:?><div class="trust-muted">Not recorded</div><?php endif;?></div>
</div></div>
<div class="foot"><div>Final Total: <b style="color:#8B1A1A">₹<?=number_format((float)$o['final_total'],2)?></b><div style="font-size:11px;color:#888">Rent ₹<?=number_format((float)$o['total_rent'],2)?> · Deposit ₹<?=number_format((float)$o['security_deposit'],2)?> · Delivery ₹<?=number_format((float)$o['delivery_charge'],2)?></div></div><?php if($o['late_charges']>0):?><div style="color:#DC2626">⚠️ Late Charges: ₹<?=number_format($o['late_charges'],0)?></div><?php elseif($o['status']==='completed'):?><div style="color:#16A34A">✅ Returned · <a href="review.php?order_id=<?=$o['id']?>" style="color:#8B1A1A">Review item</a></div><?php endif;?></div></div></div><?php endforeach; else:?><div class="empty"><div style="font-size:56px">🛍️</div><h2>No orders yet</h2><p>Browse our stores and place your first rental order</p><a href="home.php">Browse Stores</a></div><?php endif; ?>
</div></body></html>