<?php
session_start();require_once '../shared/config.php';requireLogin('customer','login.php');$db=getDB();
$stmt=$db->prepare("SELECT o.*,i.name item_name,i.image_path,v.store_name FROM orders o JOIN items i ON o.item_id=i.id JOIN vendors v ON o.vendor_id=v.id WHERE o.customer_id=? ORDER BY o.created_at DESC");$stmt->execute([$_SESSION['customer_id']]);$orders=$stmt->fetchAll();
$buyStmt=$db->prepare("SELECT po.*,poi.item_id,poi.quantity,poi.unit_price,poi.total_price,i.name item_name,i.image_path,v.store_name
    FROM purchase_orders po
    JOIN purchase_order_items poi ON poi.order_id=po.id
    JOIN items i ON i.id=poi.item_id
    LEFT JOIN vendors v ON v.id=po.vendor_id
    WHERE po.customer_id=? ORDER BY po.created_at DESC");
$buyStmt->execute([$_SESSION['customer_id']]);$buyOrders=$buyStmt->fetchAll();
$labels=['new'=>'⏳ New Order','in_progress'=>'🚀 In Progress / Rented','completed'=>'✅ Completed / Returned'];
?><!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My Orders – O2O Tradition</title><style>
body{font-family:Arial,sans-serif;background:#FAF6EE;color:#3D2B0F;margin:0}.nav{height:64px;background:#1A1108;color:#C9A84C;display:flex;align-items:center;justify-content:space-between;padding:0 40px}.logo{font:28px Georgia,serif}.nav a{color:#E8CC82;text-decoration:none;margin-left:15px}.header{background:#fff;padding:30px 40px;border-bottom:1px solid #E8E0D0}.title{font:34px Georgia,serif}.main{max-width:900px;margin:auto;padding:30px 40px}.card{background:#fff;margin-bottom:20px;box-shadow:0 2px 12px #0000000f}.head,.foot{padding:14px 20px;border-bottom:1px solid #E8E0D0;display:flex;justify-content:space-between}.body{padding:20px;display:flex;gap:16px}.img{width:80px;height:80px;background:#E8E0D0;display:flex;align-items:center;justify-content:center;font-size:28px}.img img{width:80px;height:80px;object-fit:cover}.name{font:20px Georgia,serif}.store{color:#C9A84C;font-size:12px;margin:5px 0 10px}.meta{color:#666;font-size:13px;display:flex;gap:18px;flex-wrap:wrap}.foot{border-top:1px solid #E8E0D0;border-bottom:0;background:#FDFAF5}.status{padding:5px 10px;border-radius:20px;font-size:12px}.empty{text-align:center;padding:70px;color:#888}.empty a{display:inline-block;margin-top:15px;padding:12px 24px;background:#1A1108;color:#C9A84C;text-decoration:none}@media(max-width:650px){.main{padding:20px}.nav,.header{padding-left:20px;padding-right:20px}}</style></head><body>
<div class="nav"><div class="logo">O2O Tradition</div><div><a href="home.php">Home</a><a href="logout.php">Logout</a></div></div><div class="header"><div class="title">My Orders</div><div><?=count($orders)+count($buyOrders)?> order(s) placed · <?=count($orders)?> rent · <?=count($buyOrders)?> buy</div></div><div class="main">
<h2 style="font:28px Georgia,serif;margin:0 0 18px">🛍 Buy Orders</h2>
<?php if($buyOrders): foreach($buyOrders as $o): ?>
<div class="card"><div class="head"><div>Buy Order #<?=str_pad($o['id'],6,'0',STR_PAD_LEFT)?><div style="font-size:12px;color:#aaa"><?=date('d M Y, h:i A',strtotime($o['created_at']))?></div></div><div class="status"><?=htmlspecialchars(ucfirst($o['order_status']))?></div></div>
<div class="body"><div class="img"><?php if($o['image_path']&&file_exists('../uploads/items/'.$o['image_path'])):?><img src="../uploads/items/<?=htmlspecialchars($o['image_path'])?>"><?php else:?>🛍️<?php endif;?></div><div><div class="name"><?=htmlspecialchars($o['item_name'])?></div><div class="store">🏬 <?=htmlspecialchars($o['store_name']??'Marketplace seller')?></div><div class="meta"><span>🔢 Quantity: <b><?=intval($o['quantity'])?></b></span><span>💳 <b>Cash on Delivery</b></span><span>📦 Payment: <b><?=htmlspecialchars($o['payment_status'])?></b></span></div></div></div>
<div class="foot"><div>Purchase Total: <b style="color:#8B1A1A">₹<?=number_format($o['total_price'],0)?></b></div><div>Order Status: <b><?=htmlspecialchars(ucfirst($o['order_status']))?></b></div></div></div>
<?php endforeach; else: ?><div class="empty" style="padding:30px"><p>No buy orders yet.</p></div><?php endif; ?>
<h2 style="font:28px Georgia,serif;margin:35px 0 18px">👘 Rental Orders</h2>
<?php if($orders): foreach($orders as $o): ?><div class="card"><div class="head"><div>Order #<?=str_pad($o['id'],6,'0',STR_PAD_LEFT)?><div style="font-size:12px;color:#aaa"><?=date('d M Y, h:i A',strtotime($o['created_at']))?></div></div><div class="status"><?=htmlspecialchars($labels[$o['status']]??$o['status'])?></div></div><div class="body"><div class="img"><?php if($o['image_path']&&file_exists('../uploads/items/'.$o['image_path'])):?><img src="../uploads/items/<?=htmlspecialchars($o['image_path'])?>"><?php else:?>👘<?php endif;?></div><div><div class="name"><?=htmlspecialchars($o['item_name'])?></div><div class="store">🏬 <?=htmlspecialchars($o['store_name'])?></div><div class="meta"><span>📅 Pickup: <b><?=date('d M Y',strtotime($o['pickup_date']))?></b></span><span>🔄 Return: <b><?=date('d M Y',strtotime($o['return_date']))?></b></span><span>💳 <b><?=htmlspecialchars($o['payment_method'])?></b></span></div></div></div><div class="foot"><div>Rent Total: <b style="color:#8B1A1A">₹<?=number_format($o['total_rent'],0)?></b></div><?php if($o['late_charges']>0):?><div style="color:#DC2626">⚠️ Late Charges: ₹<?=number_format($o['late_charges'],0)?></div><?php elseif($o['status']==='completed'):?><div style="color:#16A34A">✅ Returned</div><?php endif;?></div></div><?php endforeach; else:?><div class="empty"><div style="font-size:56px">🛍️</div><h2>No orders yet</h2><p>Browse our stores and place your first rental order</p><a href="home.php">Browse Stores</a></div><?php endif; ?>
</div></body></html>