<?php
session_start();require_once '../shared/config.php';require_once '../shared/security.php';
requireLogin('customer','login.php');$db=getDB();$customerId=(int)$_SESSION['customer_id'];
function tableHas(PDO $db,string $table):bool{$st=$db->prepare("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?");$st->execute([$table]);return (bool)$st->fetchColumn();}
function customerRows(PDO $db,string $table,string $column,int $id):array{if(!tableHas($db,$table))return [];$st=$db->prepare("SELECT * FROM `".$table."` WHERE `".$column."`=? LIMIT 500");$st->execute([$id]);return $st->fetchAll(PDO::FETCH_ASSOC);}
if($_SERVER['REQUEST_METHOD']==='POST'){require_once '../shared/security.php';o2oCsrfToken();o2oRequireCsrf();
$st=$db->prepare("SELECT id,name,email,phone,pincode,address,account_status,deactivated_at,email_notifications_enabled,email_verified_at,created_at FROM customers WHERE id=?");$st->execute([$customerId]);
$data=['exported_at'=>date('c'),'profile'=>$st->fetch(PDO::FETCH_ASSOC)?:[]];
foreach([['rental_orders','orders'],['purchase_orders','purchase_orders'],['reviews','reviews'],['wishlist','wishlists'],['notifications','notifications'],['rewards','rewards'],['eco_events','eco_events'],['complaints','complaints'],['user_events','user_events'],['assistant_messages','customer_assistant_messages'],['avatars','user_avatars'],['saved_complete_looks','saved_complete_looks']] as [$key,$table])$data[$key]=customerRows($db,$table,'customer_id',$customerId);
header('Content-Type: application/json; charset=UTF-8');header('Content-Disposition: attachment; filename="o2o-tradition-account-'.$customerId.'-'.date('Ymd_His').'.json"');echo json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
?><!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Privacy & Data Export</title><style>body{font-family:Arial;background:#FAF6EE;color:#3D2B0F;margin:0}.nav{background:#1A1108;color:#C9A84C;padding:18px 28px}.nav a{color:#E8CC82;margin-left:18px;text-decoration:none}.main{max-width:800px;margin:auto;padding:30px}.card{background:#fff;border:1px solid #E8E0D0;padding:24px;margin-bottom:18px}.btn{background:#1A1108;color:#C9A84C;border:0;padding:12px 18px}.small{font-size:12px;color:#777;line-height:1.6}.warn{background:#FFF7ED;border:1px solid #FED7AA;padding:13px}</style></head><body><div class="nav"><b>O2O Tradition</b><a href="account.php">Account</a><a href="home.php">Home</a></div><main class="main"><h1>Privacy & Your Data</h1><section class="card"><h2>Download your account data</h2><p>Download a JSON copy of the customer information and marketplace records currently associated with your account, including profile data, orders, saved items, notifications, rewards, reviews, complaints, eco activity, assistant messages, avatar records and saved looks.</p><form method="POST"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($_SESSION['csrf_token']??'')?>"><button class="btn">Download My Data</button></form></section><section class="card"><h2>Security exclusions</h2><p class="small">Passwords, password-reset tokens, email-verification tokens and payment gateway secrets are deliberately excluded. Uploaded image files are not embedded; their database records are included.</p></section><section class="card warn"><b>Account deletion</b><p class="small">Use Account Settings to deactivate your account. Deactivation is not the same as immediate data erasure because transaction records may need to be retained.</p></section></main></body></html>