<?php
session_start();require_once '../shared/config.php';requireLogin('customer','login.php');$db=getDB();$customerId=(int)$_SESSION['customer_id'];$pincode=trim($_SESSION['customer_pincode']??'');
$cat=[];$st=$db->prepare("SELECT i.category,COUNT(*) score FROM user_events e JOIN items i ON i.id=e.item_id WHERE e.customer_id=? AND i.category IS NOT NULL GROUP BY i.category ORDER BY score DESC LIMIT 5");$st->execute([$customerId]);foreach($st->fetchAll() as $r)$cat[$r['category']]=(int)$r['score'];
$saved=[];$st=$db->prepare("SELECT item_id FROM wishlists WHERE customer_id=?");$st->execute([$customerId]);foreach($st->fetchAll() as $r)$saved[(int)$r['item_id']]=true;
$seen=[];$st=$db->prepare("SELECT item_id,COUNT(*) score FROM user_events WHERE customer_id=? AND item_id IS NOT NULL GROUP BY item_id");$st->execute([$customerId]);foreach($st->fetchAll() as $r)$seen[(int)$r['item_id']]=(int)$r['score'];
$history=[];$st=$db->prepare("SELECT item_id,COUNT(*) score FROM orders WHERE customer_id=? GROUP BY item_id");$st->execute([$customerId]);foreach($st->fetchAll() as $r)$history[(int)$r['item_id']]=(int)$r['score'];
$st=$db->query("SELECT i.*,v.store_name,v.pincode store_pincode,
COALESCE((SELECT pm.mode FROM product_modes pm WHERE pm.item_id=i.id AND pm.available=1 ORDER BY FIELD(pm.mode,'buy','rent','sell','swap'),pm.id LIMIT 1),'rent') mode,
COALESCE((SELECT pm.price FROM product_modes pm WHERE pm.item_id=i.id AND pm.available=1 ORDER BY FIELD(pm.mode,'buy','rent','sell','swap'),pm.id LIMIT 1),i.rent_per_day) mode_price
FROM items i JOIN vendors v ON v.id=i.vendor_id
WHERE i.available=1 ORDER BY i.created_at DESC LIMIT 100");$rows=$st->fetchAll();
$scored=[];foreach($rows as $i){$score=0;$reasons=[];$id=(int)$i['id'];if(isset($saved[$id])){$score+=50;$reasons[]='saved';}if(isset($seen[$id])){$score+=min(35,$seen[$id]*10);$reasons[]='viewed';}if(isset($history[$id])){$score+=40;$reasons[]='past order';}if(isset($cat[$i['category']])){$score+=min(30,$cat[$i['category']]*8);$reasons[]='category interest';}if($pincode&&str_starts_with((string)$i['store_pincode'],substr($pincode,0,3))){$score+=20;$reasons[]='nearby pincode';}$scored[]=['item'=>$i,'score'=>$score,'reasons'=>$reasons];}
usort($scored,function($a,$b){return $b['score']<=>$a['score'] ?: strcmp($a['item']['name'],$b['item']['name']);});$scored=array_slice($scored,0,12);
?><!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Smart Recommendations v2</title><style>body{font-family:Arial;background:#FAF6EE;color:#3D2B0F;margin:0}.nav{background:#1A1108;color:#C9A84C;padding:18px 28px}.nav a{color:#E8CC82;text-decoration:none;margin-left:18px}.main{max-width:1100px;margin:auto;padding:30px}.hero,.card{background:#fff;border:1px solid #E8E0D0;padding:22px;margin-bottom:20px}.hero{background:#21170B;color:#fff}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:18px}.item{background:#fff;border:1px solid #E8E0D0;text-decoration:none;color:inherit}.pic{height:180px;background:#E8E0D0;display:flex;align-items:center;justify-content:center;font-size:55px}.pic img{width:100%;height:180px;object-fit:cover}.body{padding:14px}.name{font:22px Georgia,serif}.store{font-size:11px;color:#C9A84C;margin:5px 0}.meta{font-size:13px;color:#8B1A1A;font-weight:bold}.small{font-size:12px;color:#777;line-height:1.6}.reason{font-size:10px;color:#777;margin-top:7px}</style></head><body><div class="nav"><b>O2O Tradition</b><a href="home.php">Explore</a><a href="wishlist.php">Saved Items</a><a href="stylist.php">AI Stylist</a></div><main class="main"><section class="hero"><h1>✦ Smart Recommendations</h1><p>Recommendations are ranked using your saved items, catalogue activity, past orders, category interest and nearby pincode availability.</p></section><section class="card"><h2>Transparent recommendation signals</h2><p class="small">Higher scores come from stronger recorded signals. This is a deterministic ranking, not a claim that an item is personally guaranteed to suit you.</p></section><?php if(!$scored):?><section class="card">No available catalogue items yet.</section><?php else:?><div class="grid"><?php foreach($scored as $x):$i=$x['item'];?><a class="item" href="item.php?id=<?=$i['id']?>"><div class="pic"><?php if($i['image_path']&&file_exists('../uploads/items/'.$i['image_path'])):?><img src="../uploads/items/<?=htmlspecialchars($i['image_path'])?>" alt="<?=htmlspecialchars($i['name'])?>"><?php else:?>👘<?php endif;?></div><div class="body"><div class="name"><?=htmlspecialchars($i['name'])?></div><div class="store"><?=htmlspecialchars($i['store_name'])?></div><div class="meta"><?=htmlspecialchars(ucfirst($i['mode']))?> · ₹<?=number_format((float)$i['mode_price'],0)?></div><div class="small"><?=htmlspecialchars($i['category']??'Traditional wear')?></div><div class="reason"><?=htmlspecialchars(implode(' · ',$x['reasons']?:['catalogue availability']))?></div></div></a><?php endforeach;?></div><?php endif;?></main></body></html>