<?php
session_start();require_once '../shared/config.php';
require_once '../shared/security.php';
o2oCsrfToken();requireLogin('customer','login.php');$db=getDB();$customerId=(int)$_SESSION['customer_id'];$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  o2oRequireCsrf();
 $height=(float)($_POST['height']??0);$chest=(float)($_POST['chest']??0);$waist=(float)($_POST['waist']??0);$hip=(float)($_POST['hip']??0);$shoulder=(float)($_POST['shoulder']??0);$sleeve=(float)($_POST['sleeve']??0);$shoe=trim($_POST['shoe_size']??'');
 if($height<0||$chest<0||$waist<0||$hip<0||$shoulder<0||$sleeve<0)$error='Measurements cannot be negative.';
 else{$st=$db->prepare("INSERT INTO size_profiles(customer_id,height,chest,waist,hip,shoulder,sleeve,shoe_size) VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE height=VALUES(height),chest=VALUES(chest),waist=VALUES(waist),hip=VALUES(hip),shoulder=VALUES(shoulder),sleeve=VALUES(sleeve),shoe_size=VALUES(shoe_size)");$st->execute([$customerId,$height?:null,$chest?:null,$waist?:null,$hip?:null,$shoulder?:null,$sleeve?:null,$shoe?:null]);$message='Size profile saved.';}
}
$st=$db->prepare("SELECT * FROM size_profiles WHERE customer_id=? LIMIT 1");$st->execute([$customerId]);$profile=$st->fetch();
?><!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Size & Fit Profile – O2O Tradition</title><style>
body{font-family:Arial;background:#FAF6EE;color:#3D2B0F;margin:0}.nav{background:#1A1108;color:#C9A84C;padding:18px 28px;display:flex;justify-content:space-between}.nav a{color:#E8CC82;margin-left:15px;text-decoration:none}.main{max-width:800px;margin:auto;padding:30px}.hero,.card{background:#fff;padding:24px;margin-bottom:18px;border:1px solid #E8E0D0}.hero{background:#28170c;color:#fff}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.label{display:block;font-size:11px;font-weight:bold;margin:8px 0}.input{width:100%;padding:11px;box-sizing:border-box}.btn{margin-top:18px;padding:12px 20px;background:#1A1108;color:#C9A84C;border:0}.msg{background:#ECFDF5;color:#065F46;padding:12px}.err{background:#FEF2F2;color:#991B1B;padding:12px}@media(max-width:650px){.grid{grid-template-columns:1fr}}</style></head><body><div class="nav"><b>O2O Tradition</b><div><a href="home.php">Home</a><a href="stylist.php">AI Stylist</a></div></div><main class="main"><section class="hero"><h1>📏 Size & Fit Profile</h1><p>Save your measurements once so future O2O Tradition size and fit features can use them. Enter measurements in centimetres.</p></section><?php if($message):?><div class="msg"><?=$message?></div><?php endif;?><?php if($error):?><div class="err"><?=htmlspecialchars($error)?></div><?php endif;?><form class="card" method="POST"><div class="grid"><?php foreach(['height'=>'Height','chest'=>'Chest','waist'=>'Waist','hip'=>'Hip','shoulder'=>'Shoulder','sleeve'=>'Sleeve'] as $key=>$label):?><div><label class="label"><?=$label?> (cm)</label><input class="input" type="number" step="0.1" min="0" name="<?=$key?>" value="<?=htmlspecialchars($profile[$key]??'')?>"></div><?php endforeach;?><div><label class="label">Shoe size</label><input class="input" name="shoe_size" value="<?=htmlspecialchars($profile['shoe_size']??'')?>" placeholder="e.g. 8"></div></div><button class="btn">Save Size Profile</button></form><section class="card"><b>Privacy note:</b> These measurements are stored in your O2O Tradition account and are intended for future fit guidance. They are not an automatic guarantee that an item will fit.</section></main></body></html>