<?php
session_start();require_once '../shared/config.php';requireLogin('customer','login.php');$db=getDB();$storeId=intval($_GET['id']??0);
$st=$db->prepare("SELECT * FROM vendors WHERE id=?");$st->execute([$storeId]);$store=$st->fetch();if(!$store){header('Location: home.php');exit;}
$it=$db->prepare("SELECT i.*,
    EXISTS (SELECT 1 FROM product_modes pm WHERE pm.item_id=i.id AND pm.mode='rent' AND pm.available=1) AS rent_active,
    EXISTS (SELECT 1 FROM product_modes pm WHERE pm.item_id=i.id AND pm.mode='buy' AND pm.available=1) AS buy_active,
    EXISTS (SELECT 1 FROM product_modes pm WHERE pm.item_id=i.id AND pm.mode='sell' AND pm.available=1) AS sell_active,
    EXISTS (SELECT 1 FROM product_modes pm WHERE pm.item_id=i.id AND pm.mode='swap' AND pm.available=1) AS swap_active,
    NOT EXISTS (SELECT 1 FROM product_modes pm WHERE pm.item_id=i.id) AS legacy_rent
    FROM items i WHERE i.vendor_id=? AND i.available=1
    AND (NOT EXISTS (SELECT 1 FROM product_modes pm0 WHERE pm0.item_id=i.id)
         OR EXISTS (SELECT 1 FROM product_modes pm1 WHERE pm1.item_id=i.id AND pm1.available=1))
    ORDER BY i.name");
$it->execute([$storeId]);$items=$it->fetchAll();
?><!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($store['store_name'])?> – O2O Tradition</title><style>
body{font-family:Arial,sans-serif;background:#FAF6EE;color:#3D2B0F;margin:0}.nav{height:64px;background:#1A1108;display:flex;align-items:center;justify-content:space-between;padding:0 40px;color:#C9A84C}.logo{font:28px Georgia,serif}.nav a{color:#E8CC82;text-decoration:none;margin-left:15px}.hero{background:#1A1108;color:#fff;padding:45px 40px}.hero h1{font:40px Georgia,serif;font-weight:400;margin:10px 0}.meta{color:#bbb;display:flex;gap:20px;flex-wrap:wrap}.main{max-width:1200px;margin:auto;padding:40px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:24px}.card{background:#fff;box-shadow:0 2px 12px #0000000f}.img{height:220px;background:#E8E0D0;display:flex;align-items:center;justify-content:center;font-size:56px}.img img{width:100%;height:220px;object-fit:cover}.body{padding:18px}.name{font:20px Georgia,serif}.cat{font-size:11px;color:#C9A84C;text-transform:uppercase;margin:6px 0}.desc{font-size:13px;color:#666;line-height:1.5}.details{margin:14px 0;display:grid;grid-template-columns:1fr 1fr;gap:8px}.box{background:#FDFAF5;padding:9px;border:1px solid #E8E0D0}.label{font-size:10px;color:#999;text-transform:uppercase}.price{color:#8B1A1A;font-weight:bold}.rent{display:block;text-align:center;background:#1A1108;color:#C9A84C;padding:12px;text-decoration:none}.modes{display:flex;gap:6px;flex-wrap:wrap;margin:12px 0}.mode{font-size:10px;padding:5px 8px;border:1px solid #E8E0D0;color:#999;text-transform:uppercase;letter-spacing:.8px}.mode.live{background:#F6F0E5;color:#3D2B0F;border-color:#C9A84C}.next{font-size:10px;color:#8A6200;margin:8px 0 0}.empty{text-align:center;padding:60px;color:#888}@media(max-width:650px){.main,.hero{padding:20px}.nav{padding:0 20px}}</style></head><body>
<div class="nav"><div class="logo">O2O Tradition</div><div><a href="orders.php">My Orders</a><a href="logout.php">Logout</a></div></div><div class="hero"><a href="home.php" style="color:#C9A84C">← Back to stores</a><h1>🏬 <?=htmlspecialchars($store['store_name'])?></h1><div class="meta"><span>📍 <?=htmlspecialchars($store['address'])?></span><span>📌 <?=htmlspecialchars($store['pincode'])?></span><span>📞 <?=htmlspecialchars($store['phone'])?></span></div></div><div class="main"><h2>Available Items (<?=count($items)?>)</h2><?php if($items):?><div class="grid"><?php foreach($items as $item):?><div class="card"><div class="img"><?php if($item['image_path']&&file_exists('../uploads/items/'.$item['image_path'])):?><img src="../uploads/items/<?=htmlspecialchars($item['image_path'])?>"><?php else:?>👘<?php endif;?></div><div class="body"><div class="name"><?=htmlspecialchars($item['name'])?></div><div class="cat"><?=htmlspecialchars($item['category'])?></div><div class="modes"><?php if($item['legacy_rent']||$item['rent_active']):?><span class="mode live">Rent</span><?php endif;?><?php if($item['buy_active']):?><span class="mode live">Buy</span><?php else:?><span class="mode">Buy · Next</span><?php endif;?><?php if($item['sell_active']):?><span class="mode live">Sell</span><?php else:?><span class="mode">Sell · Next</span><?php endif;?><?php if($item['swap_active']):?><span class="mode live">Swap</span><?php else:?><span class="mode">Swap · Next</span><?php endif;?></div><div class="desc"><?=htmlspecialchars($item['description'])?></div><div class="details"><div class="box"><div class="label">Per Day</div><div class="price">₹<?=number_format($item['rent_per_day'],0)?></div></div><div class="box"><div class="label">Per Hour</div><div class="price"><?=$item['rent_per_hour']>0?'₹'.number_format($item['rent_per_hour'],0):'N/A'?></div></div><div class="box" style="grid-column:1/-1"><div class="label">Late Return</div><div style="color:#DC2626">₹<?=number_format($item['late_charge_per_day'],0)?>/day</div></div></div><?php if($item['legacy_rent']||$item['rent_active']):?><a class="rent" href="order.php?item_id=<?=$item['id']?>">Rent This Item</a><?php else:?><div class="next">This item is currently listed in a future marketplace mode.</div><?php endif;?></div></div><?php endforeach;?></div><?php else:?><div class="empty">📦<h3>No items available</h3><p>This store hasn't added any items yet.</p></div><?php endif;?></div></body></html>