<?php
session_start();require_once '../shared/config.php';
require_once '../shared/security.php';
o2oCsrfToken();requireLogin('customer','login.php');$db=getDB();$customerId=(int)$_SESSION['customer_id'];
if($_SERVER['REQUEST_METHOD']==='POST'){
  o2oRequireCsrf();$itemId=(int)($_POST['item_id']??0);$action=$_POST['action']??'';
  if($itemId>0){
    if($action==='add'){$db->prepare("INSERT IGNORE INTO wishlists(customer_id,item_id,availability_alert,price_alert,last_notified_price) SELECT ?,?,1,1,rent_per_day FROM items WHERE id=?")->execute([$customerId,$itemId,$itemId]);}
    elseif($action==='remove'){$db->prepare("DELETE FROM wishlists WHERE customer_id=? AND item_id=?")->execute([$customerId,$itemId]);}
    elseif($action==='alerts'){
      $availability=isset($_POST['availability_alert'])?1:0;$price=isset($_POST['price_alert'])?1:0;
      $db->prepare("UPDATE wishlists SET availability_alert=?,price_alert=? WHERE customer_id=? AND item_id=?")->execute([$availability,$price,$customerId,$itemId]);
    }
  }
  header('Location: wishlist.php');exit;
}
$st=$db->prepare("SELECT i.*,v.store_name,w.created_at saved_at,w.availability_alert,w.price_alert,w.last_notified_price FROM wishlists w JOIN items i ON i.id=w.item_id JOIN vendors v ON v.id=i.vendor_id WHERE w.customer_id=? AND i.available=1 ORDER BY w.created_at DESC");$st->execute([$customerId]);$items=$st->fetchAll();
?><!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Saved Items – O2O Tradition</title><style>body{font-family:Arial;background:#FAF6EE;color:#3D2B0F;margin:0}.nav{background:#1A1108;color:#C9A84C;padding:18px 28px}.nav a{color:#E8CC82;text-decoration:none;margin-left:18px}.main{max-width:1050px;margin:auto;padding:30px}.hero,.card{background:#fff;border:1px solid #E8E0D0;padding:20px;margin-bottom:18px}.hero{background:#21170B;color:#fff}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:18px}.item{background:#fff;border:1px solid #E8E0D0}.pic{height:190px;background:#E8E0D0;display:flex;align-items:center;justify-content:center;font-size:50px}.pic img{width:100%;height:190px;object-fit:cover}.body{padding:14px}.name{font:22px Georgia,serif}.store{font-size:11px;color:#C9A84C;margin:5px 0}.meta{font-size:12px;color:#777}.btn{display:inline-block;padding:9px 12px;background:#1A1108;color:#C9A84C;text-decoration:none;border:0;margin-top:10px}.remove{background:#7F1D1D;color:#fff;float:right}.empty{text-align:center;padding:55px;color:#888}</style></head><body><div class="nav"><b>O2O Tradition</b><a href="home.php">Home</a><a href="recommendations.php">For You</a></div><main class="main"><section class="hero"><h1>♡ Saved Items</h1><p>Keep products you want to revisit. Saved items can also become a signal for future recommendations.</p></section><?php if($items):?><div class="grid"><?php foreach($items as $i):?><div class="item"><div class="pic"><?php if($i['image_path']&&file_exists('../uploads/items/'.$i['image_path'])):?><img src="../uploads/items/<?=htmlspecialchars($i['image_path'])?>"><?php else:?>👘<?php endif;?></div><div class="body"><div class="name"><?=htmlspecialchars($i['name'])?></div><div class="store"><?=htmlspecialchars($i['store_name'])?></div><div class="meta"><?=htmlspecialchars($i['category']??'Traditional wear')?> · ₹<?=number_format((float)$i['rent_per_day'],0)?>/day</div><a class="btn" href="item.php?id=<?=$i['id']?>">View Item</a><form method="POST" style="margin-top:8px;padding:9px;background:#FAF6EE"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($_SESSION['csrf_token'])?>"><input type="hidden" name="item_id" value="<?=$i['id']?>"><input type="hidden" name="action" value="alerts"><label style="font-size:11px"><input type="checkbox" name="availability_alert" <?=$i['availability_alert']?'checked':''?>> Availability alert</label><br><label style="font-size:11px"><input type="checkbox" name="price_alert" <?=$i['price_alert']?'checked':''?>> Price-drop alert</label><br><button class="btn" style="margin-top:6px">Save Alerts</button></form><form method="POST" style="display:inline">
<input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token']) ?>"><input type="hidden" name="item_id" value="<?=$i['id']?>"><input type="hidden" name="action" value="remove"><button class="btn remove">Remove</button></form></div></div><?php endforeach;?></div><?php else:?><div class="card empty">No saved items yet.<br><a class="btn" href="home.php">Explore Catalogue</a></div><?php endif;?></main></body></html>